# Optimizer configuration
optimizer_type: ""
use_8bit_adam: false
use_lion_optimizer: false

learning_rates:
  base: 2.0e-6
  unet: null
  text_encoders: null
  blocks: null

scheduler:
  lr_scheduler: "constant"
  lr_scheduler_type: ""
  lr_scheduler_args: []
  lr_warmup_steps: 0
  lr_decay_steps: 0
  lr_scheduler_num_cycles: 1
  lr_scheduler_power: 1.0
  lr_scheduler_timescale: null
  lr_scheduler_min_lr_ratio: null

max_grad_norm: 1.0
optimizer_args: []
fused_backward_pass: false
optimizer_schedulefree_wrapper: false
schedulefree_wrapper_args: null
fused_optimizer_groups: null
