network_dim: null
network_alpha: 1.0
network_dropout: null
network_weights: null
network_module: null
network_args: null
network_train_unet_only: false
network_train_text_encoder_only: false
dim_from_weights: false
scale_weight_norms: null
base_weights: null
base_weights_multiplier: null
training_comment: null
unet_lr: null
text_encoder_lr: null
orthograd_targets:
  [
    "lora_down.weight",
    "lora_up.weight",
    "lora_down1.weight",
    "lora_up1.weight",
    "lora_down2.weight",
    "lora_up2.weight",
    "a1.weight",
    "a2.weight",
    "b1.weight",
    "b2.weight",
    "c1.weight",
  ]
