train_data_dir: null
dataset_config: null
cache_info: false
shuffle_caption: false
caption_separator: ","
caption_extension: ".caption"
caption_extention: null
keep_tokens: 0
keep_tokens_separator: ""
secondary_separator: null
enable_wildcard: false
caption_prefix: null
caption_suffix: null
color_aug: false
flip_aug: false
face_crop_aug_range: null
random_crop: false
debug_dataset: false
resolution: "512,512"
cache_latents: false
vae_batch_size: 1
cache_latents_to_disk: false
skip_cache_check: false
enable_bucket: false
min_bucket_reso: 256
max_bucket_reso: 1024
bucket_reso_steps: 64
bucket_no_upscale: false
resize_interpolation: null
token_warmup_min: 1
token_warmup_step: 0.0
alpha_mask: false
dataset_class: null
caption_dropout_rate: 0.0
caption_dropout_every_n_epochs: 0
caption_tag_dropout_rate: 0.0
reg_data_dir: null
in_json: null
dataset_repeats: 1
weighted_captions: false
