defaults:
  - optimizer: default
  - data: default
  - model: default
  - peft: default
  - training: default
  - output: default
  - performance: default
  - loss: default
  - timestep: default
  - validation: default
