---
name: Typos

on:
  push:
    branches:
      - dev-upstream
      - hydra-config-refactor
  pull_request:
    branches:
      - dev-upstream
      - hydra-config-refactor

# CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # https://woodruffw.github.io/zizmor/audits/#artipacked
          persist-credentials: false

      - name: typos-action
        uses: crate-ci/typos@v1.28.1
